--liquibase formatted sql
--changeset author:initial-data

INSERT INTO property_value (id, property_id, value) VALUES (18, 11, 'Сливочный сыр');
INSERT INTO property_value (id, property_id, value) VALUES (19, 11, 'Абрикосы');
INSERT INTO property_value (id, property_id, value) VALUES (20, 11, 'Авокадо');
INSERT INTO property_value (id, property_id, value) VALUES (21, 11, 'Ананас');
INSERT INTO property_value (id, property_id, value) VALUES (24, 11, 'Анчоусы');
INSERT INTO property_value (id, property_id, value) VALUES (25, 11, 'Апельсины');
INSERT INTO property_value (id, property_id, value) VALUES (26, 11, 'Багет французский');
INSERT INTO property_value (id, property_id, value) VALUES (27, 11, 'Базилик');
INSERT INTO property_value (id, property_id, value) VALUES (28, 11, 'Баклажаны');
INSERT INTO property_value (id, property_id, value) VALUES (29, 11, 'Баранина');
INSERT INTO property_value (id, property_id, value) VALUES (30, 11, 'Бекон');
INSERT INTO property_value (id, property_id, value) VALUES (31, 11, 'Белокочанная капуста');
INSERT INTO property_value (id, property_id, value) VALUES (32, 11, 'Бисквитная основа для торта');
INSERT INTO property_value (id, property_id, value) VALUES (33, 11, 'Фасоль');
INSERT INTO property_value (id, property_id, value) VALUES (34, 11, 'Ваниль');
INSERT INTO property_value (id, property_id, value) VALUES (36, 11, 'Варенье');
INSERT INTO property_value (id, property_id, value) VALUES (37, 11, 'Ветчина');
INSERT INTO property_value (id, property_id, value) VALUES (38, 11, 'Вино белое сухое');
INSERT INTO property_value (id, property_id, value) VALUES (39, 11, 'Вишня');
INSERT INTO property_value (id, property_id, value) VALUES (40, 11, 'Вода');
INSERT INTO property_value (id, property_id, value) VALUES (41, 11, 'Говядина');
INSERT INTO property_value (id, property_id, value) VALUES (42, 11, 'Горчица');
INSERT INTO property_value (id, property_id, value) VALUES (46, 11, 'Грибы');
INSERT INTO property_value (id, property_id, value) VALUES (47, 11, 'Груши');
INSERT INTO property_value (id, property_id, value) VALUES (48, 11, 'Джем');
INSERT INTO property_value (id, property_id, value) VALUES (50, 11, 'Дрожжи');
INSERT INTO property_value (id, property_id, value) VALUES (52, 11, 'Дыня');
INSERT INTO property_value (id, property_id, value) VALUES (53, 11, 'Ежевика');
INSERT INTO property_value (id, property_id, value) VALUES (55, 11, 'Ёрш речной');
INSERT INTO property_value (id, property_id, value) VALUES (56, 11, 'Желатин');
INSERT INTO property_value (id, property_id, value) VALUES (58, 11, 'Желток яичный');
INSERT INTO property_value (id, property_id, value) VALUES (63, 11, 'Зеленый горошек');
INSERT INTO property_value (id, property_id, value) VALUES (66, 11, 'Зефир');
INSERT INTO property_value (id, property_id, value) VALUES (67, 11, 'Изюм');
INSERT INTO property_value (id, property_id, value) VALUES (68, 11, 'Икра');
INSERT INTO property_value (id, property_id, value) VALUES (72, 11, 'Имбирь');
INSERT INTO property_value (id, property_id, value) VALUES (74, 11, 'Индейка');
INSERT INTO property_value (id, property_id, value) VALUES (76, 11, 'Инжир');
INSERT INTO property_value (id, property_id, value) VALUES (77, 11, 'Йогурт');
INSERT INTO property_value (id, property_id, value) VALUES (86, 11, 'Капуста краснокочанная');
INSERT INTO property_value (id, property_id, value) VALUES (87, 11, 'Капуста цветная');
INSERT INTO property_value (id, property_id, value) VALUES (88, 11, 'Картофель');
INSERT INTO property_value (id, property_id, value) VALUES (90, 11, 'Квас хлебный');
INSERT INTO property_value (id, property_id, value) VALUES (91, 11, 'Кефир');
INSERT INTO property_value (id, property_id, value) VALUES (94, 11, 'Килька');
INSERT INTO property_value (id, property_id, value) VALUES (95, 11, 'Кислота лимонная');
INSERT INTO property_value (id, property_id, value) VALUES (96, 11, 'Колбаса деревенская');
INSERT INTO property_value (id, property_id, value) VALUES (97, 11, 'Корень сельдерея');
INSERT INTO property_value (id, property_id, value) VALUES (98, 11, 'Кофе натуральный');
INSERT INTO property_value (id, property_id, value) VALUES (99, 11, 'Креветки очищенные');
INSERT INTO property_value (id, property_id, value) VALUES (100, 11, 'Крупа манная');
INSERT INTO property_value (id, property_id, value) VALUES (101, 11, 'Куриные желудки');
INSERT INTO property_value (id, property_id, value) VALUES (102, 11, 'Лавровый лист');
INSERT INTO property_value (id, property_id, value) VALUES (103, 11, 'Ликер ежевичный');
INSERT INTO property_value (id, property_id, value) VALUES (104, 11, 'Лимоны');
INSERT INTO property_value (id, property_id, value) VALUES (105, 11, 'Листья цикория');
INSERT INTO property_value (id, property_id, value) VALUES (106, 11, 'Лук зеленый');
INSERT INTO property_value (id, property_id, value) VALUES (107, 11, 'Лук репчатый');
INSERT INTO property_value (id, property_id, value) VALUES (108, 11, 'Лук салатный');
INSERT INTO property_value (id, property_id, value) VALUES (109, 11, 'Лук-порей');
INSERT INTO property_value (id, property_id, value) VALUES (110, 11, 'Лук-шалот');
INSERT INTO property_value (id, property_id, value) VALUES (111, 11, 'Майонез');
INSERT INTO property_value (id, property_id, value) VALUES (112, 11, 'Маслины');
INSERT INTO property_value (id, property_id, value) VALUES (113, 11, 'Масло арахисовое');
INSERT INTO property_value (id, property_id, value) VALUES (114, 11, 'Масло оливковое');
INSERT INTO property_value (id, property_id, value) VALUES (115, 11, 'Масло растительное');
INSERT INTO property_value (id, property_id, value) VALUES (116, 11, 'Масло рафинированное');
INSERT INTO property_value (id, property_id, value) VALUES (117, 11, 'Масло сливочное');
INSERT INTO property_value (id, property_id, value) VALUES (118, 11, 'Масло сливочное топленое');
INSERT INTO property_value (id, property_id, value) VALUES (119, 11, 'Мед');
INSERT INTO property_value (id, property_id, value) VALUES (121, 11, 'Миндаль');
INSERT INTO property_value (id, property_id, value) VALUES (122, 11, 'Молоко');
INSERT INTO property_value (id, property_id, value) VALUES (124, 11, 'Морковь');
INSERT INTO property_value (id, property_id, value) VALUES (125, 11, 'Мука пшеничная');
INSERT INTO property_value (id, property_id, value) VALUES (126, 11, 'Мясной бульон');
INSERT INTO property_value (id, property_id, value) VALUES (131, 11, 'Ножки куриные');
INSERT INTO property_value (id, property_id, value) VALUES (132, 11, 'Овощной бульон');
INSERT INTO property_value (id, property_id, value) VALUES (133, 11, 'Огурцы маринованные');
INSERT INTO property_value (id, property_id, value) VALUES (134, 11, 'Огурцы соленые');
INSERT INTO property_value (id, property_id, value) VALUES (136, 11, 'Орех мускатный');
INSERT INTO property_value (id, property_id, value) VALUES (137, 11, 'Орехи');
INSERT INTO property_value (id, property_id, value) VALUES (138, 11, 'Орехи грецкие');
INSERT INTO property_value (id, property_id, value) VALUES (139, 11, 'Паста томатная');
INSERT INTO property_value (id, property_id, value) VALUES (140, 11, 'Перец болгарский');
INSERT INTO property_value (id, property_id, value) VALUES (141, 11, 'Перец желтый свежий');
INSERT INTO property_value (id, property_id, value) VALUES (142, 11, 'Перец зеленый');
INSERT INTO property_value (id, property_id, value) VALUES (143, 11, 'Перец красный молотый');
INSERT INTO property_value (id, property_id, value) VALUES (144, 11, 'Перец розовый');
INSERT INTO property_value (id, property_id, value) VALUES (145, 11, 'Перец халапеньо');
INSERT INTO property_value (id, property_id, value) VALUES (146, 11, 'Перец черный молотый');
INSERT INTO property_value (id, property_id, value) VALUES (147, 11, 'Перец чили');
INSERT INTO property_value (id, property_id, value) VALUES (148, 11, 'Персики');
INSERT INTO property_value (id, property_id, value) VALUES (149, 11, 'Петрушка');
INSERT INTO property_value (id, property_id, value) VALUES (150, 11, 'Печень трески');
INSERT INTO property_value (id, property_id, value) VALUES (151, 11, 'Печенье');
INSERT INTO property_value (id, property_id, value) VALUES (152, 11, 'Помидоры');
INSERT INTO property_value (id, property_id, value) VALUES (158, 11, 'Редис');
INSERT INTO property_value (id, property_id, value) VALUES (159, 11, 'Редька');
INSERT INTO property_value (id, property_id, value) VALUES (160, 11, 'Репа');
INSERT INTO property_value (id, property_id, value) VALUES (161, 11, 'Рис');
INSERT INTO property_value (id, property_id, value) VALUES (163, 11, 'Ром');
INSERT INTO property_value (id, property_id, value) VALUES (164, 11, 'Рыба холодного копчения');
INSERT INTO property_value (id, property_id, value) VALUES (165, 11, 'Салат зеленый');
INSERT INTO property_value (id, property_id, value) VALUES (168, 11, 'Сахар');
INSERT INTO property_value (id, property_id, value) VALUES (169, 11, 'Сахар ванильный');
INSERT INTO property_value (id, property_id, value) VALUES (170, 11, 'Свекла');
INSERT INTO property_value (id, property_id, value) VALUES (171, 11, 'Сливки');
INSERT INTO property_value (id, property_id, value) VALUES (175, 11, 'Сок лимонный');
INSERT INTO property_value (id, property_id, value) VALUES (177, 11, 'Сок яблочный');
INSERT INTO property_value (id, property_id, value) VALUES (178, 11, 'Соль');
INSERT INTO property_value (id, property_id, value) VALUES (180, 11, 'Соус');
INSERT INTO property_value (id, property_id, value) VALUES (183, 11, 'Сыр');
INSERT INTO property_value (id, property_id, value) VALUES (184, 11, 'Сыр домашний');
INSERT INTO property_value (id, property_id, value) VALUES (185, 11, 'Сыр пармезан тертый');
INSERT INTO property_value (id, property_id, value) VALUES (186, 11, 'Сыр фета');
INSERT INTO property_value (id, property_id, value) VALUES (187, 11, 'Сыр эдам');
INSERT INTO property_value (id, property_id, value) VALUES (188, 11, 'Сыр эмменталь');
INSERT INTO property_value (id, property_id, value) VALUES (189, 11, 'Творог');
INSERT INTO property_value (id, property_id, value) VALUES (191, 11, 'Телятина');
INSERT INTO property_value (id, property_id, value) VALUES (192, 11, 'Тесто дрожжевое');
INSERT INTO property_value (id, property_id, value) VALUES (193, 11, 'Тимьян');
INSERT INTO property_value (id, property_id, value) VALUES (194, 11, 'Тмин');
INSERT INTO property_value (id, property_id, value) VALUES (195, 11, 'Тунец консервированный в собственном соку');
INSERT INTO property_value (id, property_id, value) VALUES (196, 11, 'Угорь');
INSERT INTO property_value (id, property_id, value) VALUES (197, 11, 'Укроп');
INSERT INTO property_value (id, property_id, value) VALUES (198, 11, 'Уксус');
INSERT INTO property_value (id, property_id, value) VALUES (199, 11, 'Уксус бальзамический');
INSERT INTO property_value (id, property_id, value) VALUES (200, 11, 'Уксус винный');
INSERT INTO property_value (id, property_id, value) VALUES (201, 11, 'Уксус рисовый');
INSERT INTO property_value (id, property_id, value) VALUES (202, 11, 'Уксус яблочный');
INSERT INTO property_value (id, property_id, value) VALUES (203, 11, 'Улитки');
INSERT INTO property_value (id, property_id, value) VALUES (204, 11, 'Урюк');
INSERT INTO property_value (id, property_id, value) VALUES (205, 11, 'Утка');
INSERT INTO property_value (id, property_id, value) VALUES (206, 11, 'Фарш мясной');
INSERT INTO property_value (id, property_id, value) VALUES (209, 11, 'Фасоль зеленая стручковая');
INSERT INTO property_value (id, property_id, value) VALUES (210, 11, 'Филе птицы');
INSERT INTO property_value (id, property_id, value) VALUES (212, 11, 'Филе рыбное');
INSERT INTO property_value (id, property_id, value) VALUES (214, 11, 'Финики');
INSERT INTO property_value (id, property_id, value) VALUES (215, 11, 'Фрукты');
INSERT INTO property_value (id, property_id, value) VALUES (216, 11, 'Хек');
INSERT INTO property_value (id, property_id, value) VALUES (217, 11, 'Хлеб белый');
INSERT INTO property_value (id, property_id, value) VALUES (218, 11, 'Хлеб бородинский');
INSERT INTO property_value (id, property_id, value) VALUES (219, 11, 'Хлеб содовый');
INSERT INTO property_value (id, property_id, value) VALUES (220, 11, 'Хлопья кукурузные');
INSERT INTO property_value (id, property_id, value) VALUES (221, 11, 'Хмели-сунели');
INSERT INTO property_value (id, property_id, value) VALUES (222, 11, 'Хрен');
INSERT INTO property_value (id, property_id, value) VALUES (223, 11, 'Цветки цукини');
INSERT INTO property_value (id, property_id, value) VALUES (224, 11, 'Цедра апельсина');
INSERT INTO property_value (id, property_id, value) VALUES (225, 11, 'Цедра лимонная');
INSERT INTO property_value (id, property_id, value) VALUES (227, 11, 'Цукаты');
INSERT INTO property_value (id, property_id, value) VALUES (228, 11, 'Цукини');
INSERT INTO property_value (id, property_id, value) VALUES (231, 11, 'Черника');
INSERT INTO property_value (id, property_id, value) VALUES (232, 11, 'Чернослив');
INSERT INTO property_value (id, property_id, value) VALUES (233, 11, 'Чеснок');
INSERT INTO property_value (id, property_id, value) VALUES (234, 11, 'Чечевица');
INSERT INTO property_value (id, property_id, value) VALUES (236, 11, 'Шалфей');
INSERT INTO property_value (id, property_id, value) VALUES (238, 11, 'Шампиньоны');
INSERT INTO property_value (id, property_id, value) VALUES (239, 11, 'Шафран');
INSERT INTO property_value (id, property_id, value) VALUES (241, 11, 'Шоколад горький');
INSERT INTO property_value (id, property_id, value) VALUES (242, 11, 'Шпик');
INSERT INTO property_value (id, property_id, value) VALUES (243, 11, 'Шпинат');
INSERT INTO property_value (id, property_id, value) VALUES (244, 11, 'Шпроты');
INSERT INTO property_value (id, property_id, value) VALUES (245, 11, 'Щавель');
INSERT INTO property_value (id, property_id, value) VALUES (250, 11, 'Щука');
INSERT INTO property_value (id, property_id, value) VALUES (251, 11, 'Щупальце осьминога');
INSERT INTO property_value (id, property_id, value) VALUES (257, 11, 'Эспрессо');
INSERT INTO property_value (id, property_id, value) VALUES (260, 11, 'Яблоки');
INSERT INTO property_value (id, property_id, value) VALUES (261, 11, 'Ягоды');
INSERT INTO property_value (id, property_id, value) VALUES (263, 11, 'Язык говяжий');
INSERT INTO property_value (id, property_id, value) VALUES (264, 11, 'Яичный белок');
INSERT INTO property_value (id, property_id, value) VALUES (265, 11, 'Яйцо куриное');
INSERT INTO property_value (id, property_id, value) VALUES (266, 11, 'Яйцо перепелиное');