--liquibase formatted sql
--changeset author:initial-data

INSERT INTO property (id, name, type, mandatory) VALUES (11, 'Ингредиенты', 'LIST', TRUE);

ALTER TABLE property_value ADD COLUMN p_id BIGINT;

INSERT INTO property_value (id, property_id, value, root_value) VALUES (nextval('seq_parent'), 11, 'Мясо и мясные продукты', TRUE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Баранина', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Бекон', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Ветчина', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Говядина', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Телятина', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Фарш мясной', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Язык говяжий', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Колбаса деревенская', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Мясной бульон', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Свинина', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Ветчина', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Шпик', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Субпродукты', FALSE);

INSERT INTO property_value (id, property_id, value, root_value) VALUES (nextval('seq_parent'), 11, 'Молочные продукты', TRUE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Сливочный сыр', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Йогурт', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Молоко', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Сливки', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Сыр', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Сыр домашний', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Сыр пармезан тертый', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Сыр фета', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Сыр эдам', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Сыр эмменталь', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Творог', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Мороженое', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Ряженка', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Кефир', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Айран', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Масло сливочное', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Масло сливочное топленое', FALSE);

INSERT INTO property_value (id, property_id, value, root_value) VALUES (nextval('seq_parent'), 11, 'Рыба и морские продукты', TRUE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Лосось', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Сёмга', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Форель', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Угорь', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Карп', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Сибас', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Дорадо', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Речная рыба', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Морская рыба', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Анчоусы', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Ёрш речной', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Креветки очищенные', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Мясо краба', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Шпроты', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Щупальце осьминога', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Щука', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Икра красная', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Хек', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Килька', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Тунец консервированный', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Устрицы', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Филе рыбное', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Печень трески', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Рыба холодного копчения', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Рыба горячего копчения', FALSE);

INSERT INTO property_value (id, property_id, value, root_value) VALUES (nextval('seq_parent'), 11, 'Мясо птицы и яйца', TRUE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Индейка', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Куриное филе', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Филе птицы', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Утка', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Яичный белок', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Яйцо куриное', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Яйцо перепелиное', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Желток яичный', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Субпродукты', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Ножки куриные', FALSE);

INSERT INTO property_value (id, property_id, value, root_value) VALUES (nextval('seq_parent'), 11, 'Овощи и приправы', TRUE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Баклажаны', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Белокочанная капуста', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Фасоль', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Зеленый горошек', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Капуста краснокочанная', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Капуста цветная', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Картофель', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Имбирь', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Корень сельдерея', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Лук зеленый', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Лук репчатый', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Лук салатный', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Лук-порей', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Лук-шалот', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Шпинат', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Щавель', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Укроп', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Овощной бульон', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Перец болгарский', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Перец желтый свежий', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Перец зеленый', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Перец красный молотый', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Перец розовый', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Перец халапеньо', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Перец черный молотый', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Перец чили', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Помидоры', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Редис', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Редька', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Репа', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Огурцы', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Салат зеленый', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Цукини', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Хрен', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Чеснок', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Огурцы маринованные', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Огурцы соленые', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Морковь', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Паста томатная', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Петрушка', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Укроп', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Тархун', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Кинза', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Свекла', FALSE);

INSERT INTO property_value (id, property_id, value, root_value) VALUES (nextval('seq_parent'), 11, 'Мучные изделия', TRUE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Печенье', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Сдобное тесто', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Песочное тесто', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Слоеное тесто', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Багет французский', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Бисквитная основа для торта', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Хлеб белый', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Хлеб черный', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Хлеб зерновой', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Хлеб бородинский', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Хлеб содовый', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Мука пшеничная', FALSE);

INSERT INTO property_value (id, property_id, value, root_value) VALUES (nextval('seq_parent'), 11, 'Фрукты и ягоды', TRUE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Абрикосы', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Авокадо', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Ананас', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Апельсины', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Бананы', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Груши', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Киви', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Малина', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Клубника', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Смородина', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Дыня', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Ежевика', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Изюм', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Виноград', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Вишня', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Груши', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Яблоки', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Ягоды', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Инжир', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Маслины', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Цедра апельсина', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Цедра лимонная', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Черника', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Чернослив', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Цукаты', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Урюк', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Персики', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Нектарины', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Лимоны', FALSE);

INSERT INTO property_value (id, property_id, value, root_value) VALUES (nextval('seq_parent'), 11, 'Соусы и приправы', TRUE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Майонез', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Чесночный соус', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Горчица', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Базилик', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Ваниль', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Уксус', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Уксус бальзамический', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Уксус винный', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Уксус рисовый', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Уксус яблочный', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Дрожжи', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Желатин', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Кислота лимонная', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Лавровый лист', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Масло арахисовое', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Масло оливковое', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Масло растительное', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Масло рафинированное', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Листья цикория', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Хмели-сунели', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Шалфей', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Шафран', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Тимьян', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Тмин', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Соль', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Сахар', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Сахар ванильный', FALSE);

INSERT INTO property_value (id, property_id, value, root_value) VALUES (nextval('seq_parent'), 11, 'Орехи и семена', TRUE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Миндаль', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Арахис', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Грецкий орех', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Фундук', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Семена подсолнечника', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Семена тыквы', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Кунжут', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Орех мускатный', FALSE);

INSERT INTO property_value (id, property_id, value, root_value) VALUES (nextval('seq_parent'), 11, 'Напитки', TRUE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Вино белое', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Вино красное', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Вино розовое', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Вино игристое', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Вода', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Кофе натуральный', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Квас хлебный', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Чай черный', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Чай зеленый', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Пиво', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Ром', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Сок лимонный', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Сок яблочный', FALSE);

INSERT INTO property_value (id, property_id, value, root_value) VALUES (nextval('seq_parent'), 11, 'Сладкое', TRUE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Варенье', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Джем', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Зефир', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Мед', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Шоколад белый', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Шоколад молочный', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Шоколад чёрный', FALSE);

INSERT INTO property_value (id, property_id, value, root_value) VALUES (nextval('seq_parent'), 11, 'Бакалея', TRUE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Крупа', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Макароны', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Спагетти', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Фарфалле', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Крупа манная', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Гречневая крупа', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Чечевица', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Бобы', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Рис', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Хлопья кукурузные', FALSE);

INSERT INTO property_value (id, property_id, value, root_value) VALUES (nextval('seq_parent'), 11, 'Грибы', TRUE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Шампиньоны', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Белые грибы', FALSE);
INSERT INTO property_value (id, p_id, property_id, value, root_value) VALUES (nextval('seq'), currval('seq_parent'), 11, 'Вешенки', FALSE);

INSERT INTO value_value (parent_id, child_id) SELECT
                                                p_id,
                                                id
                                              FROM property_value where root_value=false;
ALTER TABLE property_value DROP COLUMN p_id;

